### PR TITLE
Tidying up after Release of FLIMfit 4.8.0

### PR DESCRIPTION
**Pull request by imunro**
No rush to merge Josh. Just wanted to make this available to you.

### CODE REVIEW

**Comment by joshmoore** [comment]
Thank you, sir. In general, I'd go for remove rather than comment out, but happy to merge at your leisure.

**Comment by imunro** [comment]
Me too but I just presented Paul with a list of three options for what to tackle next & there's a 33% chance he'll pick doing plates "properly" (i.e. in an OME way) in which case that code will get fixed v soon.

**Comment by imunro** [comment]
FYI Sent the following to Paul yesterday:
"We then need to decide what's next from (in no particular order)
1)  Modify FLIMfit to be able to handle "proper" i.e. OME style plates.
2) Update FLIMfit to work with OMERO 5.1.
3) Look at super-resolution.  "
& got "I think I prefer 1) then 3) then 2)" so the Plate/screen stuff will be back in shortly.

**Comment by joshmoore** [comment]
Merging after discussion with @imunro. I'll try to get this pushed to bintray for use in maven.

**Pull request merged**
