### PR TITLE
Allow FLIMfit to use single-step Attachment selection developed for SMLM tools.

### PR DESCRIPTION
**Pull request by imunro**
Allow FLIMfit to use single-step Attachment selection developed for SMLM tools.

### CODE REVIEW

**Comment by joshmoore** [comment]
Closing & re-opening to activate travis.

**Comment by joshmoore** [comment]
Merging, but note that travis has some warnings:

```
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 75, column 17
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 64, column 17
```

See https://travis-ci.org/joshmoore/ome-ui-utils/builds/112791313

**Comment by joshmoore** [comment]
See https://bintray.com/joshmoore/maven/ome-ui-utils/0.1.3

**Comment by imunro** [comment]
Many thanks & Hmmm! Wonder what that's about.

**Pull request merged**
